
name: skinbot

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch: {}      


concurrency:
  group: skinbot
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  bot:
    runs-on: ubuntu-latest
    timeout-minutes: 350     
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Instalar dependencias
        run: pip install discord.py requests

      - name: Arrancar el bot
        env:
          MFSB_TOKEN: ${{ secrets.MFSB_TOKEN }}
          MFSB_GH_TOKEN: ${{ secrets.MFSB_GH_TOKEN }}
          MFSB_ADMINS: ${{ secrets.MFSB_ADMINS }}
          MFSB_CHANNEL: ${{ secrets.MFSB_CHANNEL }}
          MFSB_REPO: ${{ github.repository }} 
          MFSB_ACC_REPO: ${{ secrets.MFSB_ACC_REPO }}
          MFSB_MOD_REPO: ${{ secrets.MFSB_MOD_REPO }}
          MFSB_MOD_PATH: ${{ secrets.MFSB_MOD_PATH }}
        run: python ai/discord_skinbot.py
